[project]
name = "legislative-events-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash>=2.18.2",
    "dash-bootstrap-components>=1.7.1",
]
